import path from "node:path";
import { Cron } from "croner";
import type { Db } from "../db/db.js";
import type { MordomoPaths } from "../paths.js";
import type { Settings } from "../config/schema.js";
import type { RunManager, RunRecord } from "../runs/runManager.js";
import type { SkillCatalog } from "../skills/catalog.js";
import { RoutineStore, nextRunAt } from "./store.js";
import type { Routine, RoutineStatus } from "./types.js";

/**
 * Internal scheduler (documented fallback + default engine).
 * Runs inside the MordomoOS service process: routines fire while the service is
 * up. OS-level units (systemd --user / launchd / Task Scheduler) generated by
 * os-integration.ts keep the service itself alive so this engine is always on.
 *
 * Catch-up: on start, any enabled routine with missedPolicy=run_on_boot whose
 * last firing is older than its previous scheduled slot fires once.
 */
export class RoutineScheduler {
  private jobs = new Map<string, Cron>();
  private running = false;

  constructor(
    private readonly db: Db,
    private readonly paths: MordomoPaths,
    private readonly store: RoutineStore,
    private readonly runs: RunManager,
    private readonly skills: SkillCatalog,
    private readonly getSettings: () => Settings,
  ) {}

  start(): void {
    this.running = true;
    this.reload();
    this.catchUpMissed();
  }

  stop(): void {
    this.running = false;
    for (const job of this.jobs.values()) job.stop();
    this.jobs.clear();
  }

  /** Re-read routine files and rebuild cron jobs. Call after any CRUD change. */
  reload(): void {
    if (!this.running) return;
    for (const job of this.jobs.values()) job.stop();
    this.jobs.clear();
    for (const routine of this.store.list()) {
      if (!routine.enabled) continue;
      const job = new Cron(
        routine.schedule,
        { timezone: routine.timezone, protect: true },
        () => void this.fire(routine.id, "fired", Date.now()),
      );
      this.jobs.set(routine.id, job);
    }
  }

  private catchUpMissed(): void {
    const now = Date.now();
    for (const routine of this.store.list()) {
      if (!routine.enabled || routine.missedPolicy !== "run_on_boot") continue;
      const previous = previousScheduledTime(routine, now);
      if (!previous) continue;
      const last = this.lastFiring(routine.id);
      if (!last || last < previous) {
        this.recordHistory(routine.id, null, previous, "caught_up", "Missed while the service was off; fired on boot per policy.");
        void this.fire(routine.id, "caught_up", previous, true);
      }
    }
  }

  /** Fire a routine now (scheduler tick, catch-up, or manual test run). */
  async fire(
    routineId: string,
    reason: "fired" | "caught_up" | "manual",
    scheduledFor: number | null,
    historyAlreadyRecorded = false,
  ): Promise<RunRecord | null> {
    const routine = this.store.get(routineId);
    if (!routine) return null;
    const settings = this.getSettings();

    let prompt: string;
    let skillSlug: string | null = null;
    let mode: "read_only" | "write" = routine.profile === "read_only" ? "read_only" : "write";
    const run = this.runs.create({
      origin: "routine",
      provider: routine.provider,
      prompt: routine.prompt ?? `(skill: ${routine.skillSlug})`,
      cwd: routine.workingDir ?? this.paths.home,
      model: routine.model ?? settings.providers[routine.provider].defaultModel,
      effort: routine.effort,
      mode,
      timeoutMs: routine.timeoutMs,
      profile: routine.profile,
      skillSlug: routine.skillSlug,
      routineId: routine.id,
    });

    if (routine.skillSlug) {
      const skill = this.skills.load(routine.skillSlug);
      if (!skill) {
        this.recordHistory(routine.id, run.id, scheduledFor, "failed_to_fire", `Skill "${routine.skillSlug}" not found.`);
        await this.runs.cancel(run.id);
        return this.runs.get(run.id);
      }
      skillSlug = skill.slug;
      const artifactsDir = path.join(this.paths.artifacts, run.id);
      prompt = this.skills.buildRunPrompt(skill, routine.inputs, artifactsDir);
      if (skill.mode === "read_only") mode = "read_only";
    } else {
      prompt = [
        routine.prompt ?? "",
        `Write any produced file into: ${path.join(this.paths.artifacts, run.id)}`,
      ].join("\n\n");
    }

    if (!historyAlreadyRecorded) {
      this.recordHistory(routine.id, run.id, scheduledFor, reason === "manual" ? "fired" : reason, reason === "manual" ? "Manual test run." : null);
    } else {
      this.db.prepare("UPDATE routine_history SET run_id = ? WHERE routine_id = ? AND run_id IS NULL AND fired_at = (SELECT MAX(fired_at) FROM routine_history WHERE routine_id = ?)").run(run.id, routine.id, routine.id);
    }

    // Retries with backoff
    let attempt = 0;
    let record: RunRecord | null = null;
    while (attempt < routine.maxAttempts) {
      attempt++;
      record = await this.runs.execute(run.id, prompt, mode);
      if (record.status === "done" || record.status === "cancelled") break;
      if (attempt < routine.maxAttempts) {
        await sleep(routine.backoffMs * attempt);
        this.db.prepare("UPDATE runs SET status = 'queued', attempts = ? WHERE id = ?").run(attempt + 1, run.id);
      }
    }
    void skillSlug;
    return record;
  }

  private lastFiring(routineId: string): number | null {
    const row = this.db
      .prepare("SELECT MAX(fired_at) m FROM routine_history WHERE routine_id = ? AND status IN ('fired','caught_up')")
      .get(routineId) as { m: number | null };
    return row.m;
  }

  private recordHistory(
    routineId: string,
    runId: string | null,
    scheduledFor: number | null,
    status: string,
    note: string | null,
  ): void {
    this.db
      .prepare("INSERT INTO routine_history (routine_id, run_id, scheduled_for, fired_at, status, note) VALUES (?, ?, ?, ?, ?, ?)")
      .run(routineId, runId, scheduledFor, Date.now(), status, note);
  }

  history(routineId: string, limit = 20): Array<{ id: number; runId: string | null; scheduledFor: number | null; firedAt: number; status: string; note: string | null }> {
    const rows = this.db
      .prepare("SELECT * FROM routine_history WHERE routine_id = ? ORDER BY fired_at DESC LIMIT ?")
      .all(routineId, limit) as Array<{ id: number; run_id: string | null; scheduled_for: number | null; fired_at: number; status: string; note: string | null }>;
    return rows.map((r) => ({ id: r.id, runId: r.run_id, scheduledFor: r.scheduled_for, firedAt: r.fired_at, status: r.status, note: r.note }));
  }

  status(): RoutineStatus[] {
    return this.store.list().map((routine) => {
      const lastRow = this.db
        .prepare(
          `SELECT h.fired_at, COALESCE(r.status, h.status) AS status
           FROM routine_history h LEFT JOIN runs r ON r.id = h.run_id
           WHERE h.routine_id = ? ORDER BY h.fired_at DESC LIMIT 1`,
        )
        .get(routine.id) as { fired_at: number; status: string } | undefined;
      const failures = (
        this.db
          .prepare(
            `SELECT COUNT(*) c FROM routine_history h JOIN runs r ON r.id = h.run_id
             WHERE h.routine_id = ? AND r.status = 'failed' AND h.fired_at > ?`,
          )
          .get(routine.id, Date.now() - 3 * 86_400_000) as { c: number }
      ).c;
      return {
        ...routine,
        nextRunAt: nextRunAt(routine),
        lastFiredAt: lastRow?.fired_at ?? null,
        lastStatus: lastRow?.status ?? null,
        recentFailures: failures,
        healthy: failures < 2,
      };
    });
  }
}

function previousScheduledTime(routine: Routine, now: number): number | null {
  try {
    // Walk back: find the most recent scheduled slot before `now` by scanning
    // next runs from (now - 7 days).
    const job = new Cron(routine.schedule, { timezone: routine.timezone, paused: true });
    let cursor = new Date(now - 7 * 86_400_000);
    let previous: number | null = null;
    for (let i = 0; i < 4000; i++) {
      const next = job.nextRun(cursor);
      if (!next || next.getTime() >= now) break;
      previous = next.getTime();
      cursor = new Date(next.getTime() + 1000);
    }
    job.stop();
    return previous;
  } catch {
    return null;
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
