import path from "node:path";
import { writeDecision } from "../security/profiles.js";
import { Cron } from "croner";
import type { Db } from "../db/db.js";
import type { MordomoPaths } from "../paths.js";
import type { Settings } from "../config/schema.js";
import type { RunManager, RunRecord } from "../runs/runManager.js";
import type { SkillCatalog } from "../skills/catalog.js";
import type { RoutineStore } from "./store.js";
import type { Routine, RoutineStatus } from "./types.js";
import { JsonlLogger } from "../logs/jsonl.js";
import { events } from "../events.js";

/**
 * Internal scheduler (documented fallback + default engine).
 * Runs inside the MordomoOS service process: routines fire while the service is
 * up. OS-level units (systemd --user / launchd / Task Scheduler) generated by
 * os-integration.ts keep the service itself alive so this engine is always on.
 *
 * Catch-up: on start, any enabled routine with missedPolicy=run_on_boot whose
 * last firing is older than its previous scheduled slot fires once.
 *
 * Firing model: `fire()` creates the first run row and resolves immediately
 * with its id; execution (and retries, each a new run linked by parent_run_id)
 * continues in the background, tracked per routine so overlapping firings are
 * refused. The croner callback returns the whole in-flight promise so
 * `protect: true` engages as well.
 */

export type FireReason = "fired" | "caught_up" | "manual";

export interface FireOptions {
  reason?: FireReason;
  scheduledFor?: number | null;
  /** The history row was already inserted (catch-up); only fill in the run id. */
  historyAlreadyRecorded?: boolean;
}

export interface FireResult {
  runId: string;
  status: string;
}

/** Hard cap on croner steps when searching for the previous slot. */
const PREVIOUS_SLOT_MAX_STEPS = 500;

export class RoutineScheduler {
  private jobs = new Map<string, Cron>();
  private running = false;
  /** Background firing per routine: in-flight guard + what stop() drains. */
  private readonly inflight = new Map<string, Promise<void>>();
  private abort = new AbortController();
  private readonly logger: JsonlLogger;

  constructor(
    private readonly db: Db,
    private readonly paths: MordomoPaths,
    private readonly store: RoutineStore,
    private readonly runs: RunManager,
    private readonly skills: SkillCatalog,
    private readonly getSettings: () => Settings,
  ) {
    const s = getSettings();
    this.logger = new JsonlLogger(paths.logs, "scheduler", s.limits.logMaxFileBytes, s.limits.logRetentionDays);
  }


  /** Logging must never throw, even after the logs dir is gone (late background tasks). */
  private log(record: Record<string, unknown>): void {
    try {
      this.logger.append(record);
    } catch {
      /* best effort */
    }
  }

  start(): void {
    this.running = true;
    this.abort = new AbortController();
    this.reload();
    this.catchUpMissed();
  }

  /** Stop cron jobs and cancel pending backoff sleeps. In-flight runs are left to RunManager.shutdown(). */
  stop(): void {
    this.running = false;
    this.abort.abort();
    for (const job of this.jobs.values()) job.stop();
    this.jobs.clear();
  }

  /** Wait for background firings to settle (after stop() + runs.shutdown()). */
  async drain(): Promise<void> {
    await Promise.allSettled([...this.inflight.values()]);
  }

  /** Re-read routine files and rebuild cron jobs. Call after any CRUD change. */
  reload(): void {
    if (!this.running) return;
    for (const job of this.jobs.values()) job.stop();
    this.jobs.clear();
    for (const routine of this.store.list()) {
      if (!routine.enabled) continue;
      const job = new Cron(
        routine.schedule,
        {
          timezone: this.timezoneFor(routine),
          // Blocked overlapping ticks are recorded as `skipped` (croner still blocks them).
          protect: () =>
            this.safeHistory(routine.id, null, Date.now(), "skipped", "Previous firing still in flight (croner protect)."),
          catch: (err) => this.log({ event: "cron_callback_error", routineId: routine.id, error: String(err) }),
        },
        (self) => this.onTick(routine.id, self),
      );
      this.jobs.set(routine.id, job);
    }
  }

  /** Cron callback: returns the full in-flight promise so `protect` engages. */
  private async onTick(routineId: string, job: Cron): Promise<void> {
    const scheduledFor = job.currentRun()?.getTime() ?? Date.now();
    if (this.inflight.has(routineId)) {
      this.safeHistory(routineId, null, scheduledFor, "skipped", "Previous firing still in flight.");
      return;
    }
    try {
      await this.fire(routineId, { reason: "fired", scheduledFor });
    } catch (err) {
      const message = (err as Error).message;
      this.safeHistory(routineId, null, scheduledFor, "failed_to_fire", message);
      this.log({ event: "failed_to_fire", routineId, error: message });
      return;
    }
    await this.inflight.get(routineId);
  }

  private catchUpMissed(): void {
    let routines: Routine[];
    try {
      routines = this.store.list();
    } catch (err) {
      this.log({ event: "catch_up_skipped", error: (err as Error).message });
      return;
    }
    const now = Date.now();
    for (const routine of routines) {
      if (!routine.enabled || routine.missedPolicy !== "run_on_boot") continue;
      const previous = previousScheduledTime(routine.schedule, this.timezoneFor(routine), now);
      if (!previous) continue;
      const last = this.lastFiring(routine.id);
      if (last && last >= previous) continue;
      this.recordHistory(routine.id, null, previous, "caught_up", "Missed while the service was off; fired on boot per policy.");
      this.fire(routine.id, { reason: "caught_up", scheduledFor: previous, historyAlreadyRecorded: true }).catch(
        (err: Error) => {
          this.safeHistory(routine.id, null, previous, "failed_to_fire", err.message);
          this.log({ event: "failed_to_fire", routineId: routine.id, reason: "caught_up", error: err.message });
        },
      );
    }
  }

  /**
   * Fire a routine now. Resolves as soon as the first run row exists; the run
   * (and any retries) executes in the background. Throws with `statusCode`
   * 404 (unknown routine), 409 (already in flight) or 400 (missing skill).
   */
  async fire(routineId: string, opts: FireOptions = {}): Promise<FireResult> {
    const reason = opts.reason ?? "manual";
    const scheduledFor = opts.scheduledFor ?? null;
    const routine = this.store.get(routineId);
    if (!routine) throw Object.assign(new Error(`Routine not found: ${routineId}`), { statusCode: 404 });
    if (this.inflight.has(routineId)) {
      throw Object.assign(new Error(`Routine "${routineId}" is already running.`), { statusCode: 409 });
    }

    const settings = this.getSettings();
    let skillSlug: string | null = null;
    // Routines write only when the global profile allows unattended writes (audit item 39).
    let mode: "read_only" | "write" =
      routine.profile !== "read_only" && writeDecision(settings.securityProfile, "routine") === "allow" ? "write" : "read_only";
    let buildPrompt: (runId: string) => string;
    if (routine.skillSlug) {
      const skill = this.skills.load(routine.skillSlug);
      if (!skill) {
        throw Object.assign(new Error(`Skill "${routine.skillSlug}" not found.`), { statusCode: 400 });
      }
      skillSlug = skill.slug;
      if (skill.mode === "read_only") mode = "read_only";
      buildPrompt = (runId) => this.skills.buildRunPrompt(skill, routine.inputs, path.join(this.paths.artifacts, runId));
    } else {
      buildPrompt = (runId) =>
        [routine.prompt ?? "", `Write any produced file into: ${path.join(this.paths.artifacts, runId)}`].join("\n\n");
    }

    const createRun = (attempt: number, parentRunId: string | null) =>
      this.runs.create({
        origin: "routine",
        provider: routine.provider,
        prompt: routine.prompt ?? `(skill: ${skillSlug})`,
        cwd: routine.workingDir ?? this.paths.home,
        model: routine.model ?? settings.providers[routine.provider].defaultModel,
        effort: routine.effort,
        mode,
        timeoutMs: routine.timeoutMs,
        profile: mode === "write" ? routine.profile : "read_only",
        skillSlug,
        routineId: routine.id,
        parentRunId,
        attempts: attempt,
      });

    const first = createRun(1, null);
    if (opts.historyAlreadyRecorded) {
      this.db
        .prepare(
          "UPDATE routine_history SET run_id = ? WHERE routine_id = ? AND run_id IS NULL AND fired_at = (SELECT MAX(fired_at) FROM routine_history WHERE routine_id = ? AND run_id IS NULL)",
        )
        .run(first.id, routine.id, routine.id);
    } else {
      this.recordHistory(
        routine.id,
        first.id,
        scheduledFor,
        reason === "manual" ? "fired" : reason,
        reason === "manual" ? "Manual test run." : null,
      );
    }
    events.emit("routine.fired", { routineId: routine.id, runId: first.id });

    const task = this.runWithRetries(routine, first, buildPrompt, mode, createRun, scheduledFor)
      .catch((err: Error) => {
        this.log({ event: "routine_run_error", routineId: routine.id, runId: first.id, error: err.message });
      })
      .finally(() => {
        if (this.inflight.get(routine.id) === task) this.inflight.delete(routine.id);
      });
    this.inflight.set(routine.id, task);
    return { runId: first.id, status: first.status };
  }

  private async runWithRetries(
    routine: Routine,
    first: RunRecord,
    buildPrompt: (runId: string) => string,
    mode: "read_only" | "write",
    createRun: (attempt: number, parentRunId: string | null) => RunRecord,
    scheduledFor: number | null,
  ): Promise<void> {
    let current = first;
    let attempt = 1;
    for (;;) {
      const record = await this.runs.execute(current.id, buildPrompt(current.id), mode);
      const retryable =
        record.status === "failed" || (record.status === "timed_out" && routine.retryOnTimeout);
      if (!retryable || attempt >= routine.maxAttempts || this.abort.signal.aborted) return;
      const ok = await sleep(routine.backoffMs * attempt, this.abort.signal);
      if (!ok) return;
      attempt++;
      current = createRun(attempt, first.id);
      this.recordHistory(
        routine.id,
        current.id,
        scheduledFor,
        "fired",
        `Retry ${attempt}/${routine.maxAttempts} after ${record.status} (run ${record.id}).`,
      );
    }
  }

  /** Effective timezone: the routine's own, else settings.timezone, else UTC. */
  private timezoneFor(routine: Routine): string {
    return routine.timezone || this.getSettings().timezone || "UTC";
  }

  private lastFiring(routineId: string): number | null {
    const row = this.db
      .prepare("SELECT MAX(fired_at) m FROM routine_history WHERE routine_id = ? AND status IN ('fired','caught_up')")
      .get(routineId) as { m: number | null };
    return row.m;
  }

  private recordHistory(
    routineId: string,
    runId: string | null,
    scheduledFor: number | null,
    status: string,
    note: string | null,
  ): void {
    this.db
      .prepare("INSERT INTO routine_history (routine_id, run_id, scheduled_for, fired_at, status, note) VALUES (?, ?, ?, ?, ?, ?)")
      .run(routineId, runId, scheduledFor, Date.now(), status, note);
  }

  /** recordHistory that never throws (used from error paths, possibly after the DB closed). */
  private safeHistory(
    routineId: string,
    runId: string | null,
    scheduledFor: number | null,
    status: string,
    note: string | null,
  ): void {
    try {
      this.recordHistory(routineId, runId, scheduledFor, status, note);
    } catch (err) {
      this.log({ event: "history_write_failed", routineId, status, error: (err as Error).message });
    }
  }

  history(routineId: string, limit = 20): Array<{ id: number; runId: string | null; scheduledFor: number | null; firedAt: number; status: string; note: string | null }> {
    const rows = this.db
      .prepare("SELECT * FROM routine_history WHERE routine_id = ? ORDER BY fired_at DESC, id DESC LIMIT ?")
      .all(routineId, limit) as Array<{ id: number; run_id: string | null; scheduled_for: number | null; fired_at: number; status: string; note: string | null }>;
    return rows.map((r) => ({ id: r.id, runId: r.run_id, scheduledFor: r.scheduled_for, firedAt: r.fired_at, status: r.status, note: r.note }));
  }

  status(): RoutineStatus[] {
    return this.store.list().map((routine) => {
      const lastRow = this.db
        .prepare(
          `SELECT h.fired_at, COALESCE(r.status, h.status) AS status
           FROM routine_history h LEFT JOIN runs r ON r.id = h.run_id
           WHERE h.routine_id = ? ORDER BY h.fired_at DESC, h.id DESC LIMIT 1`,
        )
        .get(routine.id) as { fired_at: number; status: string } | undefined;
      const failures = (
        this.db
          .prepare(
            `SELECT COUNT(*) c FROM routine_history h JOIN runs r ON r.id = h.run_id
             WHERE h.routine_id = ? AND r.status IN ('failed','timed_out') AND h.fired_at > ?`,
          )
          .get(routine.id, Date.now() - 3 * 86_400_000) as { c: number }
      ).c;
      return {
        ...routine,
        nextRunAt: routine.enabled ? nextScheduledTime(routine.schedule, this.timezoneFor(routine)) : null,
        lastFiredAt: lastRow?.fired_at ?? null,
        lastStatus: lastRow?.status ?? null,
        recentFailures: failures,
        healthy: failures < 2,
      };
    });
  }
}

function nextScheduledTime(schedule: string, timezone: string): number | null {
  try {
    const job = new Cron(schedule, { timezone, paused: true });
    const next = job.nextRun();
    job.stop();
    return next ? next.getTime() : null;
  } catch {
    return null;
  }
}

/**
 * Most recent scheduled slot strictly before `now`. croner only enumerates
 * forwards, so: estimate the period from the next two runs, look at a window
 * of that size ending at `now`, and widen it (doubling) until it contains a
 * slot; then step forward inside the window to the last slot before `now`.
 * Bounded by PREVIOUS_SLOT_MAX_STEPS in each direction.
 */
export function previousScheduledTime(schedule: string, timezone: string, now: number): number | null {
  let job: Cron | null = null;
  try {
    job = new Cron(schedule, { timezone, paused: true });
    const n1 = job.nextRun(new Date(now));
    const n2 = n1 ? job.nextRun(n1) : null;
    let window = n1 && n2 ? Math.max(n2.getTime() - n1.getTime(), 1000) : 60_000;
    const maxWindow = 366 * 86_400_000;
    for (let i = 0; i < PREVIOUS_SLOT_MAX_STEPS && window <= maxWindow; i++) {
      const candidate = job.nextRun(new Date(now - window));
      if (candidate && candidate.getTime() < now) {
        let previous = candidate.getTime();
        for (let j = 0; j < PREVIOUS_SLOT_MAX_STEPS; j++) {
          const next = job.nextRun(new Date(previous));
          if (!next || next.getTime() >= now) break;
          previous = next.getTime();
        }
        return previous;
      }
      window *= 2;
    }
    return null;
  } catch {
    return null;
  } finally {
    job?.stop();
  }
}

/** Resolves true after `ms`, or false immediately when `signal` aborts. */
function sleep(ms: number, signal: AbortSignal): Promise<boolean> {
  if (ms <= 0) return Promise.resolve(true);
  if (signal.aborted) return Promise.resolve(false);
  return new Promise((resolve) => {
    const timer = setTimeout(() => {
      signal.removeEventListener("abort", onAbort);
      resolve(true);
    }, ms);
    const onAbort = () => {
      clearTimeout(timer);
      resolve(false);
    };
    signal.addEventListener("abort", onAbort, { once: true });
  });
}
