import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { writeDecision } from "../security/profiles.js";
import { redactSecrets } from "../security/redact.js";
import { Cron } from "croner";
import type { Db } from "../db/db.js";
import type { MordomoPaths } from "../paths.js";
import type { Settings } from "../config/schema.js";
import type { RunManager, RunRecord } from "../runs/runManager.js";
import type { SkillCatalog } from "../skills/catalog.js";
import type { RoutineStore } from "./store.js";
import type { Routine, RoutineRunner, RoutineStatus, RoutineSummary, SilentRoutine } from "./types.js";
import { isHeartbeatOk, nextRunFor, startOfDayIn } from "./schedule.js";
import { isStartupServiceInstalled, type StartupPlatform } from "./osIntegration.js";
import { JsonlLogger } from "../logs/jsonl.js";
import { events, type OsEvent } from "../events.js";

/**
 * Internal scheduler (documented fallback + default engine).
 * Runs inside the MordomoOS service process: routines fire while the service is
 * up. OS-level units (systemd --user / launchd / Task Scheduler) generated by
 * os-integration.ts keep the service itself alive so this engine is always on.
 *
 * Schedule kinds (routines v2): `cron` uses croner jobs; `at`, `every` and
 * `heartbeat` use plain timers rebuilt on every reload; `on-exit` listens to
 * `run.finished` on the events bus. See types.ts for the model.
 *
 * Catch-up: on start, any enabled cron routine with missedPolicy=run_on_boot
 * whose last firing is older than its previous scheduled slot fires once; a
 * one-shot (`at`) whose instant passed while the service was off fires once
 * under the same policy, otherwise it ends with `run_once_missed`.
 *
 * Firing model: `fire()` creates the first run row and resolves immediately
 * with its id; execution (and retries, each a new run linked by parent_run_id)
 * continues in the background, tracked per routine so overlapping firings are
 * refused. The croner callback returns the whole in-flight promise so
 * `protect: true` engages as well.
 */

export type FireReason = "fired" | "caught_up" | "manual";

export interface FireOptions {
  reason?: FireReason;
  scheduledFor?: number | null;
  /** The history row was already inserted (catch-up); only fill in the run id. */
  historyAlreadyRecorded?: boolean;
  /** Run that triggered an on-exit routine (recorded in the history note). */
  triggerRunId?: string | null;
}

export interface FireResult {
  runId: string;
  status: string;
}

export interface HistoryEntry {
  id: number;
  runId: string | null;
  scheduledFor: number | null;
  firedAt: number;
  status: string;
  note: string | null;
  /** Heartbeat outcome derived from the note: quiet (OK token seen) or alert. */
  outcome: "quiet" | "alert" | null;
  /** Final run status / duration when the run exists (joined from `runs`). */
  runStatus: string | null;
  durationMs: number | null;
}

export interface SchedulerOptions {
  /** Platform used to look for the installed OS service (tests override). */
  platform?: StartupPlatform;
  homeDir?: string;
  /** Timeout for webhook deliveries. */
  webhookTimeoutMs?: number;
}

/** Hard cap on croner steps when searching for the previous slot. */
const PREVIOUS_SLOT_MAX_STEPS = 500;
/** setTimeout cannot wait longer than this; longer waits re-arm in hops. */
const MAX_TIMER_MS = 2_147_483_647;
/** How long the "is the OS service installed?" answer is cached. */
const SERVICE_PROBE_TTL_MS = 60_000;
const HEARTBEAT_NOTE_QUIET = "[heartbeat:quiet]";
const HEARTBEAT_NOTE_ALERT = "[heartbeat:alert]";

export class RoutineScheduler {
  private jobs = new Map<string, Cron>();
  private timers = new Map<string, NodeJS.Timeout>();
  private onExitRoutines: Routine[] = [];
  private unsubscribeBus: (() => void) | null = null;
  private running = false;
  /** Background firing per routine: in-flight guard + what stop() drains. */
  private readonly inflight = new Map<string, Promise<void>>();
  private abort = new AbortController();
  private readonly logger: JsonlLogger;
  private serviceProbe: { at: number; installed: boolean } | null = null;
  private readonly opts: SchedulerOptions;

  constructor(
    private readonly db: Db,
    private readonly paths: MordomoPaths,
    private readonly store: RoutineStore,
    private readonly runs: RunManager,
    private readonly skills: SkillCatalog,
    private readonly getSettings: () => Settings,
    opts: SchedulerOptions = {},
  ) {
    const s = getSettings();
    this.opts = opts;
    this.logger = new JsonlLogger(paths.logs, "scheduler", s.limits.logMaxFileBytes, s.limits.logRetentionDays);
  }

  /** Logging must never throw, even after the logs dir is gone (late background tasks). */
  private log(record: Record<string, unknown>): void {
    try {
      this.logger.append(record);
    } catch {
      /* best effort */
    }
  }

  isRunning(): boolean {
    return this.running;
  }

  start(): void {
    this.running = true;
    this.abort = new AbortController();
    this.unsubscribeBus?.();
    this.unsubscribeBus = events.subscribe((e) => this.onBusEvent(e));
    this.reload();
    this.catchUpMissed();
  }

  /** Stop cron jobs and timers, cancel pending backoff sleeps. In-flight runs are left to RunManager.shutdown(). */
  stop(): void {
    this.running = false;
    this.abort.abort();
    this.unsubscribeBus?.();
    this.unsubscribeBus = null;
    this.clearJobs();
  }

  /** Wait for background firings to settle (after stop() + runs.shutdown()). */
  async drain(): Promise<void> {
    await Promise.allSettled([...this.inflight.values()]);
  }

  private clearJobs(): void {
    for (const job of this.jobs.values()) job.stop();
    this.jobs.clear();
    for (const timer of this.timers.values()) clearTimeout(timer);
    this.timers.clear();
    this.onExitRoutines = [];
  }

  /** Re-read routine files and rebuild cron jobs / timers. Call after any CRUD change. */
  reload(): void {
    if (!this.running) return;
    this.clearJobs();
    const now = Date.now();
    for (const routine of this.store.list()) {
      if (!routine.enabled) continue;
      switch (routine.kind) {
        case "cron":
          this.armCron(routine);
          break;
        case "at":
          this.armOneShot(routine, now);
          break;
        case "every":
        case "heartbeat":
          this.armTimer(routine.id, now);
          break;
        case "on-exit":
          this.onExitRoutines.push(routine);
          break;
      }
    }
  }

  private armCron(routine: Routine): void {
    const job = new Cron(
      routine.schedule,
      {
        timezone: this.timezoneFor(routine),
        // Blocked overlapping ticks are recorded as `skipped` (croner still blocks them).
        protect: () =>
          this.safeHistory(routine.id, null, Date.now(), "skipped", "Previous firing still in flight (croner protect)."),
        catch: (err) => this.log({ event: "cron_callback_error", routineId: routine.id, error: String(err) }),
      },
      (self) => this.onTick(routine.id, self),
    );
    this.jobs.set(routine.id, job);
  }

  /** One-shot: arm a timer while the instant is ahead; settle a missed one by policy. */
  private armOneShot(routine: Routine, now: number): void {
    const at = routine.at ? Date.parse(routine.at) : NaN;
    if (!Number.isFinite(at)) return;
    if (at > now) {
      this.armTimer(routine.id, now);
      return;
    }
    if (this.lastFiring(routine.id) !== null) {
      this.endRoutine(routine.id, "run_once_fired");
      return;
    }
    if (routine.missedPolicy === "run_on_boot") {
      this.recordHistory(routine.id, null, at, "caught_up", "One-shot missed while the service was off; fired on boot per policy.");
      this.fire(routine.id, { reason: "caught_up", scheduledFor: at, historyAlreadyRecorded: true }).catch((err: Error) => {
        this.safeHistory(routine.id, null, at, "failed_to_fire", err.message);
        this.log({ event: "failed_to_fire", routineId: routine.id, reason: "caught_up", error: err.message });
      });
      this.endRoutine(routine.id, "run_once_fired");
      return;
    }
    this.safeHistory(routine.id, null, at, "skipped", "One-shot missed while the service was off (missedPolicy: skip).");
    this.endRoutine(routine.id, "run_once_missed");
  }

  /** Timer-driven kinds (`at`, `every`, `heartbeat`): arm the next slot, hopping when it is far away. */
  private armTimer(routineId: string, now: number): void {
    const existing = this.timers.get(routineId);
    if (existing) clearTimeout(existing);
    this.timers.delete(routineId);
    const routine = this.store.get(routineId);
    if (!routine || !routine.enabled || !this.running) return;
    const next = nextRunFor(routine, now, this.getSettings().timezone || "UTC", cronNextAfterSafe);
    if (next === null) return;
    const delay = Math.min(Math.max(next - now, 0), MAX_TIMER_MS);
    const timer = setTimeout(() => {
      this.timers.delete(routineId);
      if (!this.running) return;
      const tickNow = Date.now();
      if (tickNow < next - 1000) {
        this.armTimer(routineId, tickNow); // long hop, not the slot yet
        return;
      }
      void this.onTimerTick(routineId, next);
    }, delay);
    timer.unref();
    this.timers.set(routineId, timer);
  }

  private async onTimerTick(routineId: string, scheduledFor: number): Promise<void> {
    const routine = this.store.get(routineId);
    if (!routine || !routine.enabled) return;
    if (this.inflight.has(routineId)) {
      this.safeHistory(routineId, null, scheduledFor, "skipped", "Previous firing still in flight.");
    } else {
      try {
        await this.fire(routineId, { reason: "fired", scheduledFor });
      } catch (err) {
        const message = (err as Error).message;
        this.safeHistory(routineId, null, scheduledFor, "failed_to_fire", message);
        this.log({ event: "failed_to_fire", routineId, error: message });
      }
    }
    if (routine.kind === "at") {
      this.endRoutine(routineId, "run_once_fired");
      return;
    }
    this.armTimer(routineId, Math.max(Date.now(), scheduledFor + 1));
  }

  /** Disable a routine with a reason (one-shots after firing) and announce the change. */
  private endRoutine(routineId: string, reason: string): void {
    try {
      const routine = this.store.get(routineId);
      if (!routine) return;
      this.store.save({ ...routine, enabled: false, endedReason: reason }, { allowWebhooks: this.getSettings().routines.allowWebhooks });
      const timer = this.timers.get(routineId);
      if (timer) clearTimeout(timer);
      this.timers.delete(routineId);
      events.emit("routine.changed", { id: routineId, action: "ended", reason });
    } catch (err) {
      this.log({ event: "end_routine_failed", routineId, error: (err as Error).message });
    }
  }

  /** Cron callback: returns the full in-flight promise so `protect` engages. */
  private async onTick(routineId: string, job: Cron): Promise<void> {
    const scheduledFor = job.currentRun()?.getTime() ?? Date.now();
    if (this.inflight.has(routineId)) {
      this.safeHistory(routineId, null, scheduledFor, "skipped", "Previous firing still in flight.");
      return;
    }
    try {
      await this.fire(routineId, { reason: "fired", scheduledFor });
    } catch (err) {
      const message = (err as Error).message;
      this.safeHistory(routineId, null, scheduledFor, "failed_to_fire", message);
      this.log({ event: "failed_to_fire", routineId, error: message });
      return;
    }
    await this.inflight.get(routineId);
  }

  /** `run.finished` → on-exit routines whose trigger skill matches the finished run. */
  private onBusEvent(e: OsEvent): void {
    if (e.type !== "run.finished" || this.onExitRoutines.length === 0) return;
    const payload = e.payload as { runId?: string; status?: string };
    if (!payload.runId) return;
    let run: RunRecord | null = null;
    try {
      run = this.runs.get(payload.runId);
    } catch {
      return;
    }
    if (!run || !run.skillSlug) return;
    for (const routine of this.onExitRoutines) {
      const trigger = routine.onExit;
      if (!trigger || trigger.skillSlug !== run.skillSlug) continue;
      if (run.routineId === routine.id) continue; // never re-trigger on our own run
      if (!trigger.statuses.includes(run.status)) continue;
      if (this.inflight.has(routine.id)) {
        this.safeHistory(routine.id, null, e.ts, "skipped", `Previous firing still in flight (trigger run ${run.id}).`);
        continue;
      }
      this.fire(routine.id, { reason: "fired", scheduledFor: e.ts, triggerRunId: run.id }).catch((err: Error) => {
        this.safeHistory(routine.id, null, e.ts, "failed_to_fire", err.message);
        this.log({ event: "failed_to_fire", routineId: routine.id, reason: "on-exit", error: err.message });
      });
    }
  }

  private catchUpMissed(): void {
    let routines: Routine[];
    try {
      routines = this.store.list();
    } catch (err) {
      this.log({ event: "catch_up_skipped", error: (err as Error).message });
      return;
    }
    const now = Date.now();
    for (const routine of routines) {
      if (!routine.enabled || routine.kind !== "cron" || routine.missedPolicy !== "run_on_boot") continue;
      const previous = previousScheduledTime(routine.schedule, this.timezoneFor(routine), now);
      if (!previous) continue;
      const last = this.lastFiring(routine.id);
      if (last && last >= previous) continue;
      this.recordHistory(routine.id, null, previous, "caught_up", "Missed while the service was off; fired on boot per policy.");
      this.fire(routine.id, { reason: "caught_up", scheduledFor: previous, historyAlreadyRecorded: true }).catch(
        (err: Error) => {
          this.safeHistory(routine.id, null, previous, "failed_to_fire", err.message);
          this.log({ event: "failed_to_fire", routineId: routine.id, reason: "caught_up", error: err.message });
        },
      );
    }
  }

  /**
   * Fire a routine now. Resolves as soon as the first run row exists; the run
   * (and any retries) executes in the background. Throws with `statusCode`
   * 404 (unknown routine), 409 (already in flight) or 400 (missing skill).
   */
  async fire(routineId: string, opts: FireOptions = {}): Promise<FireResult> {
    const reason = opts.reason ?? "manual";
    const scheduledFor = opts.scheduledFor ?? null;
    const routine = this.store.get(routineId);
    if (!routine) throw Object.assign(new Error(`Routine not found: ${routineId}`), { statusCode: 404 });
    if (this.inflight.has(routineId)) {
      throw Object.assign(new Error(`Routine "${routineId}" is already running.`), { statusCode: 409 });
    }

    const settings = this.getSettings();
    let skillSlug: string | null = null;
    // Routines write only when the global profile allows unattended writes (audit item 39).
    let mode: "read_only" | "write" =
      routine.profile !== "read_only" && writeDecision(settings.securityProfile, "routine") === "allow" ? "write" : "read_only";
    let buildPrompt: (runId: string) => string;
    if (routine.skillSlug) {
      const skill = this.skills.load(routine.skillSlug);
      if (!skill) {
        throw Object.assign(new Error(`Skill "${routine.skillSlug}" not found.`), { statusCode: 400 });
      }
      skillSlug = skill.slug;
      if (skill.mode === "read_only") mode = "read_only";
      buildPrompt = (runId) => this.skills.buildRunPrompt(skill, routine.inputs, path.join(this.paths.artifacts, runId));
    } else {
      buildPrompt = (runId) =>
        [routine.prompt ?? "", `Write any produced file into: ${path.join(this.paths.artifacts, runId)}`].join("\n\n");
    }
    if (routine.kind === "heartbeat" && routine.heartbeat) {
      const token = routine.heartbeat.okToken;
      const inner = buildPrompt;
      buildPrompt = (runId) =>
        [
          inner(runId),
          `This is a heartbeat check. If everything is fine and nothing needs attention, end your answer with the exact token ${token}. Otherwise describe what needs attention and do NOT print ${token}.`,
        ].join("\n\n");
    }

    const cwd = routine.context === "isolated" ? this.isolatedCwd(routine) : (routine.workingDir ?? this.paths.home);
    const createRun = (attempt: number, parentRunId: string | null) =>
      this.runs.create({
        origin: "routine",
        provider: routine.provider,
        prompt: routine.prompt ?? `(skill: ${skillSlug})`,
        cwd,
        model: routine.model ?? settings.providers[routine.provider].defaultModel,
        effort: routine.effort,
        mode,
        timeoutMs: routine.timeoutMs,
        profile: mode === "write" ? routine.profile : "read_only",
        skillSlug,
        routineId: routine.id,
        parentRunId,
        attempts: attempt,
      });

    const first = createRun(1, null);
    if (opts.historyAlreadyRecorded) {
      this.db
        .prepare(
          "UPDATE routine_history SET run_id = ? WHERE routine_id = ? AND run_id IS NULL AND fired_at = (SELECT MAX(fired_at) FROM routine_history WHERE routine_id = ? AND run_id IS NULL)",
        )
        .run(first.id, routine.id, routine.id);
    } else {
      const note =
        reason === "manual" ? "Manual test run." : opts.triggerRunId ? `Triggered by run ${opts.triggerRunId} (on-exit).` : null;
      this.recordHistory(routine.id, first.id, scheduledFor, reason === "manual" ? "fired" : reason, note);
    }
    if (routine.delivery !== "none") {
      events.emit("routine.fired", { routineId: routine.id, runId: first.id });
    }

    const task = this.runWithRetries(routine, first, buildPrompt, mode, createRun, scheduledFor)
      .then((final) => this.deliver(routine, first, final))
      .catch((err: Error) => {
        this.log({ event: "routine_run_error", routineId: routine.id, runId: first.id, error: err.message });
      })
      .finally(() => {
        if (this.inflight.get(routine.id) === task) this.inflight.delete(routine.id);
      });
    this.inflight.set(routine.id, task);
    return { runId: first.id, status: first.status };
  }

  /** Fresh working directory for `context: "isolated"` (outside the workspace; artifacts still land in artifacts/<runId>). */
  private isolatedCwd(routine: Routine): string {
    try {
      return fs.mkdtempSync(path.join(os.tmpdir(), `mordomo-${routine.id}-`));
    } catch {
      return this.paths.home;
    }
  }

  private async runWithRetries(
    routine: Routine,
    first: RunRecord,
    buildPrompt: (runId: string) => string,
    mode: "read_only" | "write",
    createRun: (attempt: number, parentRunId: string | null) => RunRecord,
    scheduledFor: number | null,
  ): Promise<RunRecord> {
    let current = first;
    let attempt = 1;
    for (;;) {
      const record = await this.runs.execute(current.id, buildPrompt(current.id), mode);
      const retryable =
        record.status === "failed" || (record.status === "timed_out" && routine.retryOnTimeout);
      if (!retryable || attempt >= routine.maxAttempts || this.abort.signal.aborted) return record;
      const ok = await sleep(routine.backoffMs * attempt, this.abort.signal);
      if (!ok) return record;
      attempt++;
      current = createRun(attempt, first.id);
      this.recordHistory(
        routine.id,
        current.id,
        scheduledFor,
        "fired",
        `Retry ${attempt}/${routine.maxAttempts} after ${record.status} (run ${record.id}).`,
      );
    }
  }

  /** Post-run delivery: heartbeat outcome, webhook POST. Never throws. */
  private async deliver(routine: Routine, first: RunRecord, final: RunRecord): Promise<void> {
    const summary = this.summaryOf(final.id);
    if (routine.kind === "heartbeat" && routine.heartbeat) {
      const quiet = final.status === "done" && isHeartbeatOk(summary, routine.heartbeat.okToken);
      const excerpt = summary.replace(/\s+/g, " ").slice(0, 200);
      this.updateNote(routine.id, first.id, quiet ? `${HEARTBEAT_NOTE_QUIET} ${excerpt}` : `${HEARTBEAT_NOTE_ALERT} ${excerpt}`);
      if (!quiet && routine.delivery !== "none") {
        events.emit("routine.alert", {
          routineId: routine.id,
          runId: final.id,
          status: final.status,
          summary: excerpt,
        });
      }
    }
    if (routine.delivery === "webhook") await this.postWebhook(routine, first, final, summary);
  }

  /** Summary text of a run's `result` event (empty when unavailable). */
  private summaryOf(runId: string): string {
    try {
      const rows = this.runs.eventsFor(runId);
      for (let i = rows.length - 1; i >= 0; i--) {
        const ev = rows[i]!.event;
        if (ev.type === "result") return ev.summary ?? "";
      }
    } catch {
      /* run events unavailable */
    }
    return "";
  }

  private async postWebhook(routine: Routine, first: RunRecord, final: RunRecord, summary: string): Promise<void> {
    const settings = this.getSettings();
    if (!settings.routines.allowWebhooks || !routine.webhookUrl) {
      this.updateNote(routine.id, first.id, "Webhook delivery skipped: routines.allowWebhooks is off.");
      return;
    }
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.opts.webhookTimeoutMs ?? 10_000);
    try {
      const res = await fetch(routine.webhookUrl, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          routineId: routine.id,
          name: routine.name,
          runId: final.id,
          status: final.status,
          durationMs: final.durationMs,
          artifacts: final.artifacts,
          summary: redactSecrets(summary).slice(0, 4000),
          firedAt: first.createdAt,
        }),
        signal: controller.signal,
      });
      if (!res.ok) this.updateNote(routine.id, first.id, `Webhook responded ${res.status}.`);
      this.log({ event: "webhook_delivered", routineId: routine.id, runId: final.id, status: res.status });
    } catch (err) {
      const message = redactSecrets((err as Error).message);
      this.updateNote(routine.id, first.id, `Webhook failed: ${message}`);
      this.log({ event: "webhook_failed", routineId: routine.id, runId: final.id, error: message });
    } finally {
      clearTimeout(timer);
    }
  }

  /** Effective timezone: the routine's own, else settings.timezone, else UTC. */
  private timezoneFor(routine: Routine): string {
    return routine.timezone || this.getSettings().timezone || "UTC";
  }

  private lastFiring(routineId: string): number | null {
    const row = this.db
      .prepare("SELECT MAX(fired_at) m FROM routine_history WHERE routine_id = ? AND status IN ('fired','caught_up')")
      .get(routineId) as { m: number | null };
    return row.m;
  }

  private recordHistory(
    routineId: string,
    runId: string | null,
    scheduledFor: number | null,
    status: string,
    note: string | null,
  ): void {
    this.db
      .prepare("INSERT INTO routine_history (routine_id, run_id, scheduled_for, fired_at, status, note) VALUES (?, ?, ?, ?, ?, ?)")
      .run(routineId, runId, scheduledFor, Date.now(), status, note);
  }

  /** recordHistory that never throws (used from error paths, possibly after the DB closed). */
  private safeHistory(
    routineId: string,
    runId: string | null,
    scheduledFor: number | null,
    status: string,
    note: string | null,
  ): void {
    try {
      this.recordHistory(routineId, runId, scheduledFor, status, note);
    } catch (err) {
      this.log({ event: "history_write_failed", routineId, status, error: (err as Error).message });
    }
  }

  /** Replace the note of the history row for a firing (never throws). */
  private updateNote(routineId: string, runId: string, note: string): void {
    try {
      this.db.prepare("UPDATE routine_history SET note = ? WHERE routine_id = ? AND run_id = ?").run(note, routineId, runId);
    } catch (err) {
      this.log({ event: "history_note_failed", routineId, runId, error: (err as Error).message });
    }
  }

  history(routineId: string, limit = 20): HistoryEntry[] {
    const rows = this.db
      .prepare(
        `SELECT h.*, r.status AS run_status, r.duration_ms AS run_duration
         FROM routine_history h LEFT JOIN runs r ON r.id = h.run_id
         WHERE h.routine_id = ? ORDER BY h.fired_at DESC, h.id DESC LIMIT ?`,
      )
      .all(routineId, limit) as Array<{
      id: number;
      run_id: string | null;
      scheduled_for: number | null;
      fired_at: number;
      status: string;
      note: string | null;
      run_status: string | null;
      run_duration: number | null;
    }>;
    return rows.map((r) => ({
      id: r.id,
      runId: r.run_id,
      scheduledFor: r.scheduled_for,
      firedAt: r.fired_at,
      status: r.status,
      note: r.note,
      outcome: r.note?.startsWith(HEARTBEAT_NOTE_QUIET) ? "quiet" : r.note?.startsWith(HEARTBEAT_NOTE_ALERT) ? "alert" : null,
      runStatus: r.run_status,
      durationMs: r.run_duration,
    }));
  }

  /** Effective runner for a routine (remote as declared; otherwise service when the OS unit is installed). */
  runnerFor(routine: Routine): RoutineRunner {
    if (routine.runner === "remote") return "remote";
    return this.serviceInstalled() ? "service" : "local";
  }

  private serviceInstalled(): boolean {
    const now = Date.now();
    if (this.serviceProbe && now - this.serviceProbe.at < SERVICE_PROBE_TTL_MS) return this.serviceProbe.installed;
    const installed = isStartupServiceInstalled(this.paths, this.opts.platform, this.opts.homeDir);
    this.serviceProbe = { at: now, installed };
    return installed;
  }

  private dayStart(now = Date.now()): number {
    return startOfDayIn(now, this.getSettings().timezone || "UTC");
  }

  status(): RoutineStatus[] {
    const now = Date.now();
    const dayStart = this.dayStart(now);
    const fallbackTz = this.getSettings().timezone || "UTC";
    return this.store.list().map((routine) => {
      const lastRow = this.db
        .prepare(
          `SELECT h.fired_at, COALESCE(r.status, h.status) AS status
           FROM routine_history h LEFT JOIN runs r ON r.id = h.run_id
           WHERE h.routine_id = ? ORDER BY h.fired_at DESC, h.id DESC LIMIT 1`,
        )
        .get(routine.id) as { fired_at: number; status: string } | undefined;
      const failures = (
        this.db
          .prepare(
            `SELECT COUNT(*) c FROM routine_history h JOIN runs r ON r.id = h.run_id
             WHERE h.routine_id = ? AND r.status IN ('failed','timed_out') AND h.fired_at > ?`,
          )
          .get(routine.id, now - 3 * 86_400_000) as { c: number }
      ).c;
      const firedToday =
        (
          this.db
            .prepare(
              "SELECT COUNT(*) c FROM routine_history WHERE routine_id = ? AND status IN ('fired','caught_up') AND fired_at >= ?",
            )
            .get(routine.id, dayStart) as { c: number }
        ).c > 0;
      return {
        ...routine,
        nextRunAt: nextRunFor(routine, now, fallbackTz, cronNextAfterSafe),
        lastFiredAt: lastRow?.fired_at ?? null,
        lastStatus: lastRow?.status ?? null,
        recentFailures: failures,
        healthy: failures < 2,
        runner: this.runnerFor(routine),
        firedToday,
      };
    });
  }

  /** "n/m fired today" plus counts per runner and kind (dashboard footer). */
  summary(): RoutineSummary {
    const now = Date.now();
    const dayEnd = this.dayStart(now) + 86_400_000;
    const all = this.status();
    const byRunner: Record<string, number> = {};
    const byKind: Record<string, number> = {};
    let firedToday = 0;
    let totalToday = 0;
    for (const r of all) {
      byRunner[r.runner] = (byRunner[r.runner] ?? 0) + 1;
      byKind[r.kind] = (byKind[r.kind] ?? 0) + 1;
      const dueToday = r.enabled && r.nextRunAt !== null && r.nextRunAt < dayEnd;
      if (r.firedToday) firedToday++;
      if (r.firedToday || dueToday) totalToday++;
    }
    return { firedToday, totalToday, byRunner, byKind };
  }

  /** Routines that did not fire successfully, or failed, inside the window (hygiene input). */
  silent(days = 30): SilentRoutine[] {
    const since = Date.now() - Math.max(1, days) * 86_400_000;
    const out: SilentRoutine[] = [];
    for (const r of this.status()) {
      const okInWindow = (
        this.db
          .prepare(
            `SELECT COUNT(*) c FROM routine_history h JOIN runs r ON r.id = h.run_id
             WHERE h.routine_id = ? AND r.status = 'done' AND h.fired_at >= ?`,
          )
          .get(r.id, since) as { c: number }
      ).c;
      const failuresInWindow = (
        this.db
          .prepare(
            `SELECT COUNT(*) c FROM routine_history h JOIN runs r ON r.id = h.run_id
             WHERE h.routine_id = ? AND r.status IN ('failed','timed_out') AND h.fired_at >= ?`,
          )
          .get(r.id, since) as { c: number }
      ).c;
      let reason: SilentRoutine["reason"] | null = null;
      if (failuresInWindow > 0) reason = "failures";
      else if (r.lastFiredAt === null) reason = "never_fired";
      else if (okInWindow === 0) reason = "no_fire_in_window";
      if (!reason) continue;
      out.push({
        id: r.id,
        name: r.name,
        enabled: r.enabled,
        kind: r.kind,
        lastFiredAt: r.lastFiredAt,
        lastStatus: r.lastStatus,
        failuresInWindow,
        reason,
      });
    }
    return out;
  }
}

/** croner "next after `from`" that never throws. */
function cronNextAfterSafe(schedule: string, timezone: string, from: number): number | null {
  try {
    const job = new Cron(schedule, { timezone, paused: true });
    const next = job.nextRun(new Date(from));
    job.stop();
    return next ? next.getTime() : null;
  } catch {
    return null;
  }
}

/**
 * Most recent scheduled slot strictly before `now`. croner only enumerates
 * forwards, so: estimate the period from the next two runs, look at a window
 * of that size ending at `now`, and widen it (doubling) until it contains a
 * slot; then step forward inside the window to the last slot before `now`.
 * Bounded by PREVIOUS_SLOT_MAX_STEPS in each direction.
 */
export function previousScheduledTime(schedule: string, timezone: string, now: number): number | null {
  let job: Cron | null = null;
  try {
    job = new Cron(schedule, { timezone, paused: true });
    const n1 = job.nextRun(new Date(now));
    const n2 = n1 ? job.nextRun(n1) : null;
    let window = n1 && n2 ? Math.max(n2.getTime() - n1.getTime(), 1000) : 60_000;
    const maxWindow = 366 * 86_400_000;
    for (let i = 0; i < PREVIOUS_SLOT_MAX_STEPS && window <= maxWindow; i++) {
      const candidate = job.nextRun(new Date(now - window));
      if (candidate && candidate.getTime() < now) {
        let previous = candidate.getTime();
        for (let j = 0; j < PREVIOUS_SLOT_MAX_STEPS; j++) {
          const next = job.nextRun(new Date(previous));
          if (!next || next.getTime() >= now) break;
          previous = next.getTime();
        }
        return previous;
      }
      window *= 2;
    }
    return null;
  } catch {
    return null;
  } finally {
    job?.stop();
  }
}

/** Resolves true after `ms`, or false immediately when `signal` aborts. */
function sleep(ms: number, signal: AbortSignal): Promise<boolean> {
  if (ms <= 0) return Promise.resolve(true);
  if (signal.aborted) return Promise.resolve(false);
  return new Promise((resolve) => {
    const timer = setTimeout(() => {
      signal.removeEventListener("abort", onAbort);
      resolve(true);
    }, ms);
    const onAbort = () => {
      clearTimeout(timer);
      resolve(false);
    };
    signal.addEventListener("abort", onAbort, { once: true });
  });
}
