import fs from "node:fs";
import path from "node:path";
import type { Db } from "../db/db.js";
import type { MordomoPaths } from "../paths.js";
import type { Settings } from "../config/schema.js";
import { fileRowFromDb, type FileRow } from "./indexer.js";
import { ensureJournal, journalSections, localDateString, readJournal, shiftDate, type JournalDay } from "./journal.js";

/**
 * Memory routers (ARMS Memory L2): a short master router plus one index per
 * area. Generated from the live index — never by moving the owner's files.
 * Written into memory/ (canonical); the sync compiler embeds them into
 * CLAUDE.md / AGENTS.md so every provider gets the same map.
 */

export interface RouterIssue {
  file: string;
  problem: string;
}

const GENERATED_HEADER = "<!-- generated by MordomoOS — edit areas/folders in Settings, then regenerate -->";
const JOURNAL_START = "<!-- journal:start -->";
const JOURNAL_END = "<!-- journal:end -->";
/** Default token budget for the journal block of the master router (chars / 4). */
export const DEFAULT_JOURNAL_BUDGET_TOKENS = 1200;

/**
 * Today's and yesterday's journal, rendered for the master router under a
 * token budget: today first, empty sections dropped, yesterday trimmed to
 * whatever budget is left. Deterministic for a given pair of files.
 */
export function renderJournalBlock(days: JournalDay[], budgetTokens: number): string[] {
  const budgetChars = Math.max(0, budgetTokens) * 4;
  const lines: string[] = [JOURNAL_START, "## Journal", "", "Recent daily notes (auto-created in `memory/journal/`). Append, never rewrite; promote with the `consolidate-memory` skill.", ""];
  let used = lines.join("\n").length;
  for (const day of days) {
    const block: string[] = [`### ${day.date}`];
    for (const section of journalSections(day.content)) {
      if (section.lines.length === 0) continue;
      block.push(`**${section.name}**`, ...section.lines, "");
    }
    if (block.length === 1) block.push("_(empty)_", "");
    let text = block.join("\n");
    const remaining = budgetChars - used;
    if (remaining <= 0) break;
    if (text.length > remaining) {
      text = `${text.slice(0, Math.max(0, remaining - 16)).trimEnd()}\n…(trimmed)\n`;
    }
    lines.push(text);
    used += text.length;
  }
  lines.push(JOURNAL_END);
  return lines;
}

export function generateRouters(
  db: Db,
  paths: MordomoPaths,
  settings: Settings,
): { written: string[] } {
  fs.mkdirSync(paths.memory, { recursive: true });
  const written: string[] = [];
  const areas = settings.areas;
  const folders = settings.indexedFolders.filter((f) => f.enabled);

  const areaFiles = new Map<string, FileRow[]>();
  for (const area of areas) {
    const rows = db
      .prepare("SELECT * FROM files WHERE area = ? ORDER BY mtime DESC LIMIT 40")
      .all(area) as Array<Record<string, unknown>>;
    areaFiles.set(area, rows.map(fileRowFromDb));
  }

  // Master router
  const lines: string[] = [
    GENERATED_HEADER,
    `# ${settings.systemName} — Master Router`,
    "",
    "This is the map of the workspace. Read ONLY the area index that matches the",
    "current task — never load everything at once. When a file moves or a new",
    "project starts, regenerate the routers (Settings → Memory → Refresh).",
    "",
    "| Area | Index | Folders |",
    "|---|---|---|",
  ];
  for (const area of areas) {
    const slug = areaSlug(area);
    const areaFolders = folders.filter((f) => f.area === area).map((f) => f.path);
    lines.push(
      `| ${area} | [${slug}.md](./areas/${slug}.md) | ${areaFolders.length ? areaFolders.join(", ") : "(no folder assigned yet)"} |`,
    );
  }
  const unassigned = folders.filter((f) => !f.area || !areas.includes(f.area));
  if (unassigned.length > 0) {
    lines.push("", "Unassigned folders (indexed, no area):", ...unassigned.map((f) => `- ${f.path}`));
  }
  const longTerm = path.join(paths.memory, "MEMORY.md");
  if (fs.existsSync(longTerm)) {
    lines.push("", `Long-term memory: [MEMORY.md](./MEMORY.md) — consolidated facts and reflections (read its section index first).`);
  }
  lines.push("", `Retrieval: ask \`mordomo recall "<question>"\` (or GET /api/memory/recall) before opening files by hand.`);
  // Journal: today (created on first access) + yesterday, under the token budget.
  const today = localDateString();
  const days: JournalDay[] = [ensureJournal(paths, today)];
  const yesterday = readJournal(paths, shiftDate(today, -1));
  if (yesterday) days.push(yesterday);
  const budget = settings.memory?.journalBudgetTokens ?? DEFAULT_JOURNAL_BUDGET_TOKENS;
  lines.push("", ...renderJournalBlock(days, budget));
  const masterPath = path.join(paths.memory, "ROUTER.md");
  fs.writeFileSync(masterPath, lines.join("\n") + "\n", "utf8");
  written.push(masterPath);

  // Area indexes — pointers, not documentation; kept under a page.
  const areasDir = path.join(paths.memory, "areas");
  fs.mkdirSync(areasDir, { recursive: true });
  for (const area of areas) {
    const files = areaFiles.get(area) ?? [];
    const areaLines: string[] = [
      GENERATED_HEADER,
      `# ${area} — Index`,
      "",
      files.length === 0
        ? "_No indexed files in this area yet. Assign a folder to this area in Settings._"
        : "Key files (most recently touched first):",
    ];
    for (const f of files.slice(0, 30)) {
      const label = f.title ? `${f.title} — ${f.name}` : f.name;
      areaLines.push(`- ${label} → \`${f.path}\``);
    }
    const areaPath = path.join(areasDir, `${areaSlug(area)}.md`);
    fs.writeFileSync(areaPath, areaLines.join("\n") + "\n", "utf8");
    written.push(areaPath);
  }
  return { written };
}

/** Detect stale routers and broken pointers (M-L2 "stale pointer" rule). */
export function checkRouters(db: Db, paths: MordomoPaths, settings: Settings): RouterIssue[] {
  const issues: RouterIssue[] = [];
  const masterPath = path.join(paths.memory, "ROUTER.md");
  if (!fs.existsSync(masterPath)) {
    issues.push({ file: masterPath, problem: "Master router missing — generate it in Settings → Memory." });
    return issues;
  }
  const files = [masterPath];
  const areasDir = path.join(paths.memory, "areas");
  if (fs.existsSync(areasDir)) {
    for (const f of fs.readdirSync(areasDir)) {
      if (f.endsWith(".md")) files.push(path.join(areasDir, f));
    }
  }
  for (const area of settings.areas) {
    const p = path.join(areasDir, `${areaSlug(area)}.md`);
    if (!fs.existsSync(p)) issues.push({ file: p, problem: `Missing index for area "${area}".` });
  }
  for (const file of files) {
    if (!fs.existsSync(file)) continue;
    const content = stripJournalBlock(fs.readFileSync(file, "utf8"));
    for (const match of content.matchAll(/`(\/[^`]+|[A-Za-z]:\\[^`]+)`/g)) {
      const target = match[1]!;
      if (!fs.existsSync(target)) {
        issues.push({ file, problem: `Broken pointer: ${target} no longer exists.` });
      }
    }
    const stat = fs.statSync(file);
    const last = lastIndexAt(db);
    if (last && stat.mtimeMs < last - 86_400_000) {
      issues.push({ file, problem: "Router is older than the last index by more than a day — regenerate." });
    }
  }
  return issues;
}

/** The journal block is free text (may quote paths that never existed) — not pointers. */
function stripJournalBlock(content: string): string {
  const start = content.indexOf(JOURNAL_START);
  const end = content.indexOf(JOURNAL_END);
  if (start === -1 || end === -1 || end < start) return content;
  return content.slice(0, start) + content.slice(end + JOURNAL_END.length);
}

function lastIndexAt(db: Db): number | null {
  const row = db.prepare("SELECT value FROM meta WHERE key = 'last_index'").get() as
    | { value: string }
    | undefined;
  return row ? (JSON.parse(row.value) as { at: number }).at : null;
}

export function areaSlug(area: string): string {
  return area
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
